version: '4.25.2'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api 
    restart: always
    ports:
      - 3001:3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgresprisma
    restart: always
    ports:
      - 5435:5432
    environment:
      - .env
    env_file:
      - .env
    volumes:
      - .data:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-prisma-docker-db